name: Lint

on:
    push:
        branches:
            - master
        paths-ignore:
            - 'src/Vendors/**'
            - 'applications/tools/**'

            # Docs
            - '**/*.md'
            - 'doc/**'

            # Editor/linter/config meta
            - '.vscode/**'
            - '.gitattributes'
    pull_request:
        branches:
            - master
        paths-ignore:
            - 'src/Vendors/**'
            - 'applications/tools/**'

            # Docs
            - '**/*.md'
            - 'doc/**'

            # Editor/linter/config meta
            - '.vscode/**'
            - '.gitattributes'
permissions:
    contents: read

jobs:
    eslint:
        name: ESLint (src)
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18'

            - name: Install dependencies
              run: npm i

            - name: Run ESLint
              run: npm run lint
